eps: 0.001
#eval_mode: False
eval_mode: True

# optimizer
lr: 0.0001
# train
data_dir: 'datasets/sportsmot_publish/dataset/trackers_gt_t/train'
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 1200
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0,1,2,3]

# Testing
eval_at: 1200
det_dir: "/home/geri/work/datasets/sportsmot_publish/dataset/detections/val/"
info_dir: '/home/geri/work/datasets/sportsmot_publish/dataset/val/'
reid_dir: "/home/geri/work/OXIT-Sport_Framework/src/submodules/diffmot/embeddings/SportsMOT/embeddings_yolox_x/"
save_dir: "/diffmot/"
eval_expname: lt_ddm_1000_deeper
high_thres: 0.6
low_thres: 0.4
w_assoc_emb: 2.0
aw_param: 1.2
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None
